FROM node:20-bullseye

WORKDIR /app/admin-app

# Install dependencies (better caching)
COPY admin-app/package*.json ./
RUN npm ci || npm install

# (Optional in dev because we mount source) Copy source:
# COPY admin-app/. .

EXPOSE 3000
CMD ["npm", "run", "dev"]
